# Outbound setup: see README.md, "Replying". Preserve the Message-ID
# generated by Outbound::Composer across delivery attempts so threading
# references identify the same stored message.
class ClientMailer < ApplicationMailer
  def outbound(message)
    @message = message
    @body_html = simple_html(@message.text_body.to_s)

    headers["In-Reply-To"] = @message.in_reply_to if @message.in_reply_to.present?
    headers["References"] = @message.references if @message.references.present?
    headers["Message-ID"] = @message.message_id if @message.message_id.present?

    @message.files.each do |file|
      attachments[file.filename.to_s] = {
        mime_type: file.content_type,
        content: file.download
      }
    end

    mail(
      from: Outbound::Composer.from_display,
      reply_to: Outbound::Composer.from_address,
      to: @message.recipients,
      cc: split_addrs(@message.cc_addrs),
      bcc: split_addrs(@message.bcc_addrs),
      subject: @message.subject
    ) do |format|
      format.text { render plain: @message.text_body.to_s }
      format.html { render html: @body_html.html_safe } # rubocop:disable Rails/OutputSafety
    end
  end

  private

  def split_addrs(value)
    value.to_s.split(/[,\n;]/).map(&:strip).reject(&:blank?).presence
  end

  def simple_html(text)
    paragraphs = text.split(/\n{2,}/).map do |para|
      lines = para.split("\n").map { |line| ERB::Util.html_escape(line) }
      "<p>#{lines.join('<br>')}</p>"
    end
    paragraphs.join("\n")
  end
end
