# Outbound setup: see README.md, "Replying". Preserve the Message-ID
# generated by Outbound::Composer across delivery attempts so threading
# references identify the same stored message.
#
# Signature ownership: the composer owns the text signature inside the
# stored text_body (so the timeline stays honest about what was sent);
# this mailer owns the HTML rendering and swaps that same spot for the
# HTML signature with the logo embedded by Content-ID, so each part
# carries the signature exactly once.
class ClientMailer < ApplicationMailer
  def outbound(message)
    @message = message
    setting = Setting.current
    signature_html = EmailSignature.html_for(setting)
    @body_html = signature_aware_html(@message, signature_html)

    headers["In-Reply-To"] = @message.in_reply_to if @message.in_reply_to.present?
    headers["References"] = @message.references if @message.references.present?
    headers["Message-ID"] = @message.message_id if @message.message_id.present?

    @message.files.each do |file|
      attachments[file.filename.to_s] = {
        mime_type: file.content_type,
        content: file.download
      }
    end
    attach_signature_logo(setting, signature_html)

    mail(
      from: Outbound::Composer.from_display,
      reply_to: Outbound::Composer.from_address,
      to: @message.recipients,
      cc: split_addrs(@message.cc_addrs),
      bcc: split_addrs(@message.bcc_addrs),
      subject: @message.subject
    ) do |format|
      format.text { render plain: @message.text_body.to_s }
      format.html { render html: @body_html.html_safe } # rubocop:disable Rails/OutputSafety
    end
  end

  private

  def split_addrs(value)
    value.to_s.split(/[,\n;]/).map(&:strip).reject(&:blank?).presence
  end

  def simple_html(text)
    paragraphs = text.split(/\n{2,}/).map do |para|
      lines = para.split("\n").map { |line| ERB::Util.html_escape(line) }
      "<p>#{lines.join('<br>')}</p>"
    end
    paragraphs.join("\n")
  end

  def signature_aware_html(message, signature_html)
    return simple_html(message.text_body.to_s) if signature_html.blank?

    parts = EmailSignature.split_body(message.text_body, template_id: message.template_id)
    if parts
      [ simple_html(parts.first.rstrip), signature_html, simple_html(parts.last.strip) ].reject(&:blank?).join("\n")
    else
      # Settings changed between compose and delivery: the stored text no
      # longer holds the current text signature, so append the HTML one.
      "#{simple_html(message.text_body.to_s)}\n#{signature_html}"
    end
  end
end
